version: "3.9"
services:
  web:
    image: "springapp"
    environment:
        BOOKSELF_DB_HOST: "172.20.0.3"
    build: .
    depends_on:
      - "database"
    ports:
      - "8888:8888"
    networks: 
        backend:
            ipv4_address: 172.20.0.2
  database:
    image: "postgres" # use latest official postgres version
    container_name: "postgres-bookself"
    environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "bookself"
        POSTGRES_DB: "bookself"
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks: 
        backend:
            ipv4_address: 172.20.0.3
networks:
    backend:
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/16