-- Create a few more test users
insert into users (email, username, password_hash) values ('test@test.test', 'testuser1', '$2a$10$.yZOfmBpdviB/CS7PWJnBu.CzZIlI9DoSj8RnOPPmyTCntupatDAG') on conflict do nothing;
insert into users (email, username, password_hash) values ('test2@test.test', 'testuser2', '$2a$10$.yZOfmBpdviB/CS7PWJnBu.CzZIlI9DoSj8RnOPPmyTCntupatDAG') on conflict do nothing;
insert into users (email, username, password_hash) values ('test3@test.test', 'testuser3', '$2a$10$.yZOfmBpdviB/CS7PWJnBu.CzZIlI9DoSj8RnOPPmyTCntupatDAG') on conflict do nothing;
insert into users (email, username, password_hash) values ('test4@test.test', 'testuser4', '$2a$10$.yZOfmBpdviB/CS7PWJnBu.CzZIlI9DoSj8RnOPPmyTCntupatDAG') on conflict do nothing;
insert into users (email, username, password_hash) values ('test5@test.test', 'testuser5', '$2a$10$.yZOfmBpdviB/CS7PWJnBu.CzZIlI9DoSj8RnOPPmyTCntupatDAG') on conflict do nothing;
insert into users (email, username, password_hash) values ('test6@test.test', 'testuser6', '$2a$10$.yZOfmBpdviB/CS7PWJnBu.CzZIlI9DoSj8RnOPPmyTCntupatDAG') on conflict do nothing;
insert into users (email, username, password_hash) values ('test7@test.test', 'testuser7', '$2a$10$.yZOfmBpdviB/CS7PWJnBu.CzZIlI9DoSj8RnOPPmyTCntupatDAG') on conflict do nothing;
insert into users (email, username, password_hash) values ('test8@test.test', 'testuser8', '$2a$10$.yZOfmBpdviB/CS7PWJnBu.CzZIlI9DoSj8RnOPPmyTCntupatDAG') on conflict do nothing;
insert into users (email, username, password_hash) values ('test9@test.test', 'testuser9', '$2a$10$.yZOfmBpdviB/CS7PWJnBu.CzZIlI9DoSj8RnOPPmyTCntupatDAG') on conflict do nothing;
insert into users (email, username, password_hash) values ('test10@test.test', 'testuser10', '$2a$10$.yZOfmBpdviB/CS7PWJnBu.CzZIlI9DoSj8RnOPPmyTCntupatDAG') on conflict do nothing;

-- Create some random lorem ipsum data
create table temp_lorem_ipsum (
    data text
);
insert into temp_lorem_ipsum(data) values (null); -- Null option
insert into temp_lorem_ipsum(data) values ('Dolor et hac semper eget sociis. Et, semper sollicitudin tincidunt congue orci ultricies vulputate eu! Risus integer mollis sagittis lectus dictum tincidunt gravida lacus fusce ad. Feugiat sed tortor magna fringilla cursus. Ante id, vivamus nisi urna at montes at class tristique nam consectetur. Sollicitudin justo dapibus consectetur malesuada id. Cubilia eros molestie dignissim. Fermentum gravida habitasse consectetur a. Rhoncus quisque praesent sollicitudin sed varius habitasse posuere himenaeos. Sed quam condimentum nunc leo.');
insert into temp_lorem_ipsum(data) values ('Luctus, praesent faucibus ullamcorper leo curabitur maecenas aptent rhoncus dictumst vel scelerisque. Dui vulputate leo pretium turpis inceptos. Habitant torquent curabitur placerat lacinia pretium, sed eleifend hendrerit. Consectetur accumsan nisl accumsan convallis mi senectus tristique curabitur viverra lorem. Consectetur nisi bibendum curae; lacinia odio per parturient malesuada. Parturient arcu laoreet condimentum ante donec. Tempor nam primis viverra sollicitudin fermentum. Ante tellus sed porttitor iaculis donec. Aenean elementum neque sollicitudin conubia lorem. A tempus egestas vulputate iaculis urna. Et sed praesent sociosqu nam sollicitudin porttitor. Augue ligula, posuere ante consectetur cubilia nunc ipsum conubia in. Dolor; mauris fringilla ligula.');
insert into temp_lorem_ipsum(data) values ('Himenaeos semper praesent vivamus! Mi, consectetur vivamus ultrices eget mollis pellentesque ante penatibus cum urna eleifend ornare. Aenean habitasse aliquam commodo tempus convallis tellus viverra fames sapien at magna iaculis. Himenaeos ac sed in consequat convallis justo porta convallis! Litora risus suscipit euismod elementum ad! Tortor tempor lacus diam hendrerit leo auctor lacinia! Nostra sodales fusce morbi. Praesent consequat montes montes nec rutrum aliquet. Integer mauris, vehicula sociis quis netus inceptos. Amet, varius class porta dui justo mi a sed morbi nunc orci mi.');
insert into temp_lorem_ipsum(data) values ('Suscipit ridiculus nullam vestibulum euismod lorem nostra! Duis eleifend rutrum class ante litora habitant montes urna elementum morbi metus. Nostra ullamcorper mattis primis, nisi natoque torquent nullam praesent purus. Dignissim venenatis feugiat inceptos. Facilisis eleifend suscipit laoreet aliquam mollis hendrerit ultricies morbi eros consequat. Ridiculus tempus dolor curae;, facilisi lacinia habitant purus iaculis eu eleifend. Purus condimentum id velit curae; ante mauris. Tortor vel scelerisque ad.');
insert into temp_lorem_ipsum(data) values ('Dis elit ad fringilla enim a. Pellentesque sit inceptos condimentum. Malesuada ante ligula velit mauris tortor? Cras quam, torquent tellus cum montes himenaeos imperdiet ante convallis nam? Sodales sem id dignissim vel purus litora platea sapien. Dui parturient iaculis duis laoreet cursus. Nullam eleifend condimentum quisque augue ultricies id lacinia nascetur cursus maecenas. Aliquam habitasse magna luctus, nostra consectetur bibendum ligula natoque porta per malesuada eget? Ultricies hendrerit purus penatibus malesuada aenean. Cursus adipiscing penatibus dictum scelerisque condimentum etiam torquent eleifend. Fames libero taciti venenatis? Rhoncus arcu habitasse malesuada habitant facilisi sagittis sem?');
insert into temp_lorem_ipsum(data) values ('Metus, viverra hac montes libero. Turpis aliquam euismod torquent ut posuere aliquet vivamus mus quam sociosqu. Mattis arcu nibh augue porta eu. Curae;, tortor praesent rutrum tempor vitae sodales facilisis fermentum mauris etiam. Pharetra dis duis purus torquent neque nec eu hac curae;. Aliquam ut, inceptos consectetur taciti. Mus ut a iaculis sem cubilia sit malesuada parturient enim velit eros fringilla. Tempor dictumst hendrerit nostra sociosqu! Lectus mollis habitant commodo fringilla. Sed dis dolor himenaeos libero ridiculus! Eros.');
insert into temp_lorem_ipsum(data) values ('Ipsum placerat mus non mollis proin dapibus sociosqu velit pharetra dui eu orci. Mauris magnis sapien ornare. Amet sociis quisque, neque vel dictumst donec. Semper netus accumsan class nisi tempor quis netus eu molestie habitasse. Sem neque nec porttitor. Arcu porttitor id elementum, dictumst rutrum curae; in arcu dictum integer inceptos. A donec egestas suspendisse aliquet, porttitor mauris! Placerat condimentum praesent potenti. Praesent cursus integer et. Rhoncus aptent in magnis, mi pulvinar dignissim nostra iaculis. Aliquet!');
insert into temp_lorem_ipsum(data) values ('Lorem orci facilisi, vitae suscipit. Magna magna velit congue proin purus; tellus nulla suspendisse justo. Porta arcu libero senectus platea et lectus dapibus. Magnis, placerat urna eros dictumst ornare nisl faucibus parturient urna dictum nascetur. Eget sit aenean bibendum malesuada vivamus, magnis et praesent! Pharetra, ac non tortor. Sagittis sollicitudin amet ac placerat ultrices primis congue dis? Ullamcorper donec curae; in iaculis blandit varius dis. Proin vulputate cras metus! Natoque nunc aptent ut porttitor semper auctor felis justo sodales fames magnis lobortis. Per sociosqu sollicitudin leo aliquet morbi! Natoque nibh.');
insert into temp_lorem_ipsum(data) values ('Pulvinar rutrum; nec erat accumsan. Fermentum, semper nullam orci praesent natoque. Donec erat facilisi suspendisse tortor. Condimentum posuere suscipit conubia magnis scelerisque risus congue arcu facilisis nullam. Viverra sapien magna mollis cursus aliquam lacinia ultrices nascetur porttitor dictumst. Duis turpis lectus nullam nunc nec nam eros turpis rhoncus pharetra. Netus tellus, facilisis vitae turpis fames nisl elementum lacus. Fermentum viverra sociosqu eu laoreet magnis proin netus leo dui nostra amet natoque! Commodo fames.');
insert into temp_lorem_ipsum(data) values ('Nibh himenaeos montes interdum. Feugiat, varius at porta at vivamus? Pellentesque rhoncus suscipit, lorem feugiat volutpat. Cum egestas sed sagittis blandit adipiscing auctor, fermentum purus lacinia. Ultricies neque luctus nullam tortor ridiculus eleifend aenean. Consectetur arcu fusce egestas vulputate ipsum ultricies nunc convallis aenean vivamus placerat! Tincidunt consectetur, aliquam nostra. Ac dis natoque pellentesque scelerisque ornare massa congue, ante primis eu. Ac arcu vitae proin congue tempus scelerisque.');
insert into temp_lorem_ipsum(data) values ('Bibendum porttitor senectus himenaeos convallis sapien at natoque ultricies penatibus nostra. Leo maecenas consectetur dapibus primis habitasse a urna nostra. Placerat rutrum inceptos velit cras ante eleifend convallis vitae primis pretium nostra auctor. Mus penatibus adipiscing posuere potenti sodales donec eget tincidunt mauris. Urna lorem blandit lacinia vehicula dignissim tortor egestas curabitur. Dis malesuada ipsum gravida viverra mauris. Arcu sociosqu nisl magna! Varius natoque platea potenti pretium dictumst amet nam consectetur. Conubia magna diam.');
insert into temp_lorem_ipsum(data) values ('Curae; sociosqu luctus aenean est cum ipsum cursus sem quam amet. Himenaeos tempus tempor pharetra feugiat euismod. Nec senectus dignissim ornare ipsum gravida est amet. Elit massa elit lectus quis proin platea duis et maecenas. Nisi hendrerit tempus aliquet venenatis. Suscipit dictum ac ultrices sem duis phasellus maecenas duis varius molestie. Lobortis elementum bibendum porta nam mi cras tincidunt porttitor.');
insert into temp_lorem_ipsum(data) values ('Pharetra eros lorem cubilia. Amet eu risus hac porta. Dictumst, auctor turpis fermentum. Tristique adipiscing tellus interdum venenatis, imperdiet ullamcorper semper nibh dictumst nunc. Consequat dolor volutpat dignissim, risus cras suspendisse integer rutrum quis elit? Class litora libero erat, dis id vehicula turpis vitae dis netus lectus? Enim lorem fringilla dui tellus nostra sociosqu quisque. Sit dignissim vel cubilia quis potenti hac egestas nisi quis varius a. Mi molestie fusce facilisis est ad vivamus turpis. Dui.');
insert into temp_lorem_ipsum(data) values ('Nullam consequat, dis pharetra malesuada orci. Potenti accumsan tempus habitasse eleifend. Ridiculus nec odio sapien pretium nisi litora cum. Ultricies pharetra tellus sociis blandit maecenas lacus quis convallis risus arcu lacinia. Turpis potenti pretium blandit luctus tempor felis potenti elementum bibendum. Venenatis ante etiam himenaeos eu et auctor turpis tempor sodales id mollis dictumst. Praesent feugiat enim parturient quis velit lobortis, euismod velit natoque. Metus ornare eget sapien class fames, dapibus nunc. Cursus cum venenatis risus!');
insert into temp_lorem_ipsum(data) values ('Morbi sociosqu hac adipiscing, consectetur nam fusce ultrices suspendisse phasellus dictum. Eleifend donec gravida libero porttitor penatibus tristique quam orci? Ridiculus rutrum magna in sociis sociosqu conubia hendrerit. Fusce aenean nullam magnis molestie vivamus mus tortor. Eget euismod taciti sociosqu scelerisque metus parturient vitae hendrerit? Lacinia porttitor cum nascetur purus iaculis quam tortor malesuada phasellus. Massa consequat eget a augue laoreet mattis interdum venenatis justo proin et donec. Nullam, justo risus odio aliquet dictum odio tempor ad.');
insert into temp_lorem_ipsum(data) values ('Imperdiet sodales elementum tincidunt, mattis nisi vel nec. Dapibus tristique suspendisse adipiscing feugiat turpis. Nam sociis potenti id risus vivamus imperdiet fringilla elit malesuada venenatis. Tristique etiam sem facilisis ante iaculis placerat dapibus natoque bibendum nibh faucibus id. Ornare maecenas maecenas eros pretium cubilia rhoncus hac. Ipsum integer elementum ante varius lobortis est vel faucibus class ante. Eu aenean vitae diam condimentum facilisi ut mauris mollis interdum luctus. Enim sagittis tristique elementum, himenaeos laoreet lorem placerat fames pellentesque euismod iaculis! Justo rutrum dictumst mauris posuere aenean ullamcorper hac. Quisque massa ullamcorper gravida.');
insert into temp_lorem_ipsum(data) values ('Venenatis feugiat laoreet placerat, litora dictumst. A cum leo curae; praesent curae; vulputate aliquet? Nam lorem lacus taciti interdum adipiscing. Malesuada, integer amet hac tempor. Duis, vestibulum in aliquet curae; mauris viverra bibendum id curae; orci consectetur lacinia. Vitae primis facilisis, est lectus elit praesent habitasse dictumst bibendum! Nisi conubia aenean felis erat. Nascetur luctus lacinia euismod. Suscipit erat dignissim faucibus sapien condimentum pretium hac cum odio? Commodo imperdiet elementum suscipit inceptos imperdiet sodales parturient condimentum class pharetra imperdiet? Proin praesent at eu. Bibendum fringilla at risus taciti bibendum, molestie ad. Tellus.');
insert into temp_lorem_ipsum(data) values ('Tortor sit montes class interdum ante parturient aenean cras venenatis vestibulum placerat! Faucibus maecenas parturient sollicitudin tortor ultricies cras curabitur vivamus tincidunt. Egestas justo tempor nam tempor enim nec. Cubilia amet iaculis blandit convallis lobortis praesent scelerisque tristique natoque parturient nunc. Aenean odio hendrerit senectus fusce nulla. Penatibus eros eleifend nunc hac natoque convallis rhoncus. Ut accumsan ut venenatis sapien magnis auctor. Sociosqu, curae; viverra in! Mi quam dictumst diam, sociis semper. Sit.');
insert into temp_lorem_ipsum(data) values ('Sit ridiculus dictum est natoque. Nulla curabitur amet metus viverra feugiat suspendisse tristique consequat primis mattis. Accumsan nam ad penatibus auctor aliquet cum sem, luctus congue viverra curae;. Eget proin adipiscing libero amet class vestibulum. Taciti facilisi taciti nisl urna nam non. Curabitur elementum nunc lobortis auctor montes libero nisi ante ultrices sociosqu in. Praesent praesent donec vestibulum eros lectus ullamcorper condimentum cras cum vulputate urna sagittis. Placerat montes justo dignissim platea. Id tempor fermentum, velit litora integer? Eleifend potenti consequat inceptos.');
insert into temp_lorem_ipsum(data) values ('Curabitur dis etiam venenatis porta. Consectetur convallis tincidunt dignissim vivamus dictum consequat. Vulputate vitae donec etiam quis consequat euismod varius magna fermentum elementum ad. Potenti hac malesuada etiam dictumst cum ultrices congue nisi cursus imperdiet tortor. Vehicula lectus dis amet lacus. Cras ullamcorper adipiscing ad ut est leo quam aenean aliquet, ad!');
insert into temp_lorem_ipsum(data) values ('Cubilia montes ad vivamus inceptos nulla in at. Lorem sollicitudin dui cum aenean etiam magna facilisis blandit. Feugiat pulvinar nascetur accumsan mus vehicula habitant interdum pretium vulputate nisl. Laoreet quisque etiam ridiculus nunc a venenatis ipsum per lorem inceptos nostra luctus. Libero cras taciti lacus felis conubia eget urna duis nisi ultrices? Sociis tempus fusce elit massa praesent. Molestie felis augue venenatis integer velit hendrerit. Vulputate aptent justo odio eget.');
insert into temp_lorem_ipsum(data) values ('Senectus libero aenean nibh penatibus class pellentesque venenatis placerat tristique orci molestie. Varius id tempus nascetur lectus luctus justo non lectus. Tristique dignissim sagittis iaculis ut habitant hendrerit habitasse dictumst tincidunt duis vulputate. At arcu dictumst venenatis cras ut aliquam porttitor ridiculus laoreet sit. Duis pellentesque tellus elementum class fames nullam aptent mus donec sagittis dictumst sociis! Dignissim sollicitudin vulputate dignissim maecenas fringilla sapien, mus felis torquent metus. Dis potenti inceptos potenti vitae ut nostra nunc aliquet conubia. Inceptos enim platea consectetur sollicitudin sollicitudin. Nibh varius iaculis massa turpis tellus condimentum etiam.');
insert into temp_lorem_ipsum(data) values ('Senectus nisi quam dui sollicitudin cubilia? Nec torquent ornare volutpat dictum volutpat. Arcu facilisis magnis dictum lectus. Sollicitudin sollicitudin justo velit cubilia netus pretium sagittis et adipiscing, laoreet maecenas. Sapien sagittis luctus mattis ante mattis. Scelerisque, erat suspendisse ultricies ac. Eleifend justo per primis mauris morbi velit lectus sem. Taciti conubia sollicitudin felis sapien suspendisse magnis. Nullam fringilla curabitur quis duis porttitor turpis interdum curae; amet fringilla venenatis morbi? Amet congue sem felis, vitae aenean habitasse. Lacinia litora gravida proin sagittis sed a congue viverra. Placerat rhoncus risus posuere ultricies! Euismod cursus rutrum eleifend malesuada pretium.');
insert into temp_lorem_ipsum(data) values ('Maecenas varius feugiat interdum habitant nisl natoque arcu accumsan nisi fames. Viverra lorem ac pellentesque lobortis, dictumst mollis. Velit lobortis blandit praesent dapibus neque imperdiet ultrices massa. Volutpat et neque tellus sagittis netus nam elementum fames elementum neque rhoncus. Pretium est fames facilisi dui purus nascetur donec etiam porta. Consectetur ipsum vulputate tincidunt inceptos ipsum lobortis tincidunt arcu. Leo, suscipit pharetra a suspendisse?');
insert into temp_lorem_ipsum(data) values ('Fermentum sed ante pharetra hendrerit urna nibh convallis ullamcorper. Blandit class imperdiet sociis mattis tincidunt porttitor vestibulum! Mi porttitor facilisis urna morbi. Mattis malesuada urna facilisis ornare. Cum orci faucibus montes suspendisse ornare varius ut. Parturient sapien tellus facilisi penatibus ante consequat tristique fames morbi, nascetur sodales. Penatibus pharetra platea lobortis dolor dictum fames fermentum lobortis. Taciti tristique habitasse consequat sapien, pellentesque eget rutrum blandit eros justo aenean eleifend. Placerat nullam eros sollicitudin pulvinar velit lacus nascetur tempor tellus litora non convallis! Varius dapibus, pretium fusce habitant elementum mi fames. Felis per amet.');
insert into temp_lorem_ipsum(data) values ('Accumsan hac quis semper convallis habitasse pellentesque lobortis metus sagittis ut. Sem arcu netus lacus metus ridiculus. Facilisis lacinia aliquam nisl venenatis nisi lacus feugiat. Diam mattis hendrerit parturient nascetur pulvinar dictum mauris euismod fermentum sem tellus! Netus consectetur ligula inceptos iaculis sociis nullam pulvinar tincidunt arcu. Vitae at netus feugiat rutrum cum eleifend ridiculus tortor montes ornare. Luctus quis netus risus dignissim lacus taciti! Euismod parturient consectetur viverra consequat id. Egestas sociis molestie litora commodo amet laoreet quis rutrum aptent? Aenean mollis, rhoncus purus. Dui fermentum.');
insert into temp_lorem_ipsum(data) values ('Montes suspendisse vestibulum ligula malesuada accumsan erat netus per diam. Aliquet nisl lectus hac bibendum sapien vulputate donec vivamus. Mi maecenas mollis eleifend tristique enim gravida ridiculus feugiat ad tellus magnis. Sapien sagittis est ipsum molestie mauris. Duis scelerisque euismod neque, nascetur gravida quisque dictum vel eleifend et. Litora ipsum mus facilisis ullamcorper elit lacus auctor. Cubilia vehicula facilisis nam aenean vivamus urna fames? Dictumst.');
insert into temp_lorem_ipsum(data) values ('Porttitor at laoreet odio non vivamus volutpat magna a nunc imperdiet ante. Nisi vehicula aliquam sollicitudin montes aliquam pellentesque maecenas hac viverra blandit. Bibendum facilisi faucibus ligula primis dictumst senectus cursus. Orci aptent curabitur velit. Arcu hac facilisis amet praesent quam consectetur sed per. Aliquet eleifend sociosqu accumsan? Suscipit dapibus integer elit proin eget tincidunt; eu natoque montes. Sodales luctus litora varius nisi fermentum pulvin''ar; varius congue. Volutpat ipsum nisi erat! Fames etiam cubilia, vestibulum et. Sagittis nisl eleifend quam class urna faucibus? Nisi, suspendisse felis ac diam vestibulum!');
insert into temp_lorem_ipsum(data) values ('Vitae ornare ultrices ornare scelerisque lacus purus suscipit ad? Pulvinar sodales, inceptos sit felis. Fermentum metus adipiscing est praesent libero orci. Vulputate tristique nec velit habitasse rutrum dui massa! Urna vestibulum urna fames. Cubilia mollis ornare ornare, diam commodo fringilla tincidunt per montes a dapibus? Pretium ut integer rhoncus faucibus quis ac vehicula porttitor luctus cubilia dapibus euismod. Montes taciti class massa eget tristique bibendum. Aliquam malesuada donec vulputate sollicitudin mollis rhoncus libero at habitasse fusce dictumst. Lacinia hendrerit mauris lorem facilisi mi semper convallis cubilia dictumst phasellus.');
insert into temp_lorem_ipsum(data) values ('Consectetur laoreet, elit sollicitudin. Per elementum ultricies molestie nibh aliquet quisque taciti eu malesuada hac nisl. Neque posuere sapien hendrerit. Cum gravida congue semper condimentum etiam ridiculus praesent porta volutpat interdum curae;. Imperdiet massa rhoncus dis accumsan adipiscing aliquet dictumst ullamcorper sem. Pretium etiam morbi dolor tincidunt dignissim vulputate. Nunc.');
insert into temp_lorem_ipsum(data) values ('Torquent tincidunt facilisis vehicula sagittis. Lectus integer lacus consequat laoreet praesent nostra habitasse dictum vestibulum fusce. Sociosqu volutpat eu pulvinar. Vivamus nisi augue, pulvinar netus. Inceptos non aenean a tincidunt aptent sed amet lectus placerat malesuada dictum! Potenti turpis aliquam fames curae; cum vestibulum etiam felis egestas! Magna in netus feugiat eu maecenas luctus urna placerat vehicula elementum? Torquent vitae nulla habitasse elit mauris sem ac porttitor hendrerit, platea magna adipiscing. Vivamus per a per magna sociosqu? Ullamcorper lectus per vehicula diam mi.');
insert into temp_lorem_ipsum(data) values ('Pulvinar cras vitae ultricies urna habitasse viverra pellentesque sagittis molestie? Cursus etiam sociosqu, cubilia platea purus habitasse arcu. Elementum senectus facilisi dictum nullam praesent! Enim cras posuere porta mi. Taciti cursus tortor sagittis, ullamcorper litora felis consectetur aptent! Dis sagittis nunc nam dapibus duis laoreet tristique. Nisi nisl netus phasellus malesuada. Netus commodo dolor adipiscing parturient nam neque. Ipsum senectus egestas nostra nascetur non feugiat dui nibh, semper est! Interdum augue dapibus pharetra donec nisl tempus et ullamcorper lobortis quis nam. Euismod sodales dis morbi quisque luctus eu cubilia curae; integer habitant. Ac aliquam cras justo nunc.');
insert into temp_lorem_ipsum(data) values ('Lorem rhoncus malesuada blandit ad iaculis sapien nunc dictumst. Primis malesuada rutrum vestibulum interdum. Elit placerat consequat cras viverra ad non. Bibendum neque eleifend aliquam nullam mi platea in porta laoreet! Phasellus blandit nisi dolor consectetur vitae dictum. Auctor, sed rutrum erat proin. Venenatis urna, bibendum non feugiat mus aliquet sollicitudin blandit porttitor. Neque eros vestibulum conubia.');
insert into temp_lorem_ipsum(data) values ('Sapien mauris dictum inceptos, maecenas elementum sit. Porttitor lacinia felis himenaeos massa laoreet faucibus scelerisque maecenas mattis ante gravida. Potenti vivamus faucibus himenaeos ac amet tempor conubia ac eu integer litora tempor! Ligula quam potenti nisi lectus. Feugiat tellus commodo cursus elit facilisis luctus cubilia. Eleifend class torquent fringilla litora eleifend condimentum vestibulum cursus quis massa. Varius blandit curabitur, montes massa. Orci tortor lobortis nisl inceptos magnis. Magnis nostra metus euismod aenean amet lectus id nec purus. Bibendum, condimentum parturient sapien interdum semper. Sit pretium aenean sociosqu aliquam.');
insert into temp_lorem_ipsum(data) values ('Laoreet fringilla tellus, morbi tincidunt proin vel dignissim! Quisque neque fusce, vitae volutpat. Eros purus himenaeos mattis congue phasellus aliquam hac odio venenatis! Litora venenatis condimentum torquent lobortis pellentesque netus facilisis venenatis, mollis congue gravida varius! Fames, lacus curae; orci urna gravida! Ultricies duis imperdiet; ante luctus. Mattis dictumst porttitor feugiat porttitor facilisis dis erat. Senectus tempus etiam cursus, porttitor per aenean rutrum nullam varius praesent nascetur id. Ultrices mus maecenas.');
insert into temp_lorem_ipsum(data) values ('Class curae; eget, justo nisi vehicula lobortis natoque! Quam parturient, hendrerit torquent luctus platea pharetra. Adipiscing cum habitant dui dictumst tincidunt; nulla venenatis. Adipiscing sapien semper magna. Aptent parturient suscipit vulputate sit parturient lacinia? Varius condimentum praesent est, malesuada sociosqu libero torquent hac torquent velit. Mauris egestas tempus, orci ligula conubia taciti laoreet fringilla facilisis quisque magnis ultricies? Eget class dignissim.');
insert into temp_lorem_ipsum(data) values ('Eget quis duis tristique aptent felis curabitur nullam maecenas, auctor justo urna augue? Lobortis magnis, auctor lacinia accumsan commodo sit? Aptent molestie leo per vestibulum pharetra sit pellentesque. Quisque congue erat interdum aptent ad facilisis eleifend porta blandit elementum consectetur risus? Varius orci torquent himenaeos tristique interdum varius cubilia habitasse magna. Nisi nec ultrices class faucibus quam, tellus cum accumsan eu auctor varius. Ad vel odio vehicula taciti.');
insert into temp_lorem_ipsum(data) values ('Natoque orci quis laoreet class pulvinar facilisis in vulputate mus quam pellentesque? Orci, ipsum justo suspendisse! Mattis risus habitasse; quisque at. Sociis libero habitant dignissim magnis tristique ipsum. Lacinia suscipit ultrices praesent nibh lacinia per metus ridiculus ut. Aliquam vulputate proin massa dictumst egestas ante nulla semper non! Parturient suspendisse suspendisse laoreet tempus ultricies. A quis mollis elit ad nascetur viverra semper pellentesque. Primis, ac potenti sit curabitur vehicula integer. Vivamus metus accumsan facilisi. Nibh dis taciti metus lobortis bibendum sollicitudin etiam hendrerit venenatis. Rhoncus proin curabitur consequat dictum dolor pulvinar?');
insert into temp_lorem_ipsum(data) values ('Vitae nisl tempus quam. Sodales adipiscing dis ipsum. Tortor pharetra consectetur aptent cursus nulla dis dis nisl libero. Tincidunt primis curabitur fermentum at duis imperdiet dis. Ligula rhoncus odio dis montes! Tortor dolor consequat non laoreet integer leo varius lobortis? Potenti sodales condimentum arcu arcu tincidunt suscipit vitae! Turpis ad volutpat ligula taciti mollis luctus donec purus quam conubia, egestas facilisi! Sit sed, eleifend integer semper porttitor lectus nunc laoreet euismod. Aptent eu, eleifend sed malesuada in montes inceptos platea est? Risus nascetur iaculis inceptos porttitor placerat in. Posuere sem torquent mollis.');
insert into temp_lorem_ipsum(data) values ('Inceptos integer morbi mollis leo quam vivamus duis sit vel. Tempor augue taciti, mus ipsum ornare. Hac eu morbi cubilia. Egestas turpis arcu sociis proin erat arcu elit pretium aptent aptent dis! Felis platea fames eu luctus ipsum justo habitant a urna luctus interdum. Est cum consectetur iaculis. Habitant tellus dignissim ad cras vulputate placerat cubilia est! Tempus justo cras etiam augue donec taciti justo ipsum? Lacus sociis vitae id. Massa pulvinar faucibus id facilisis.');
insert into temp_lorem_ipsum(data) values ('Pharetra hac aenean sociosqu natoque eleifend viverra tellus. Vulputate natoque curabitur lectus. Massa duis, eleifend diam tincidunt gravida? Nullam felis per dis sodales integer. Cum hac metus aenean ornare vehicula tempor a sagittis, vehicula vel commodo. Fusce posuere orci at ultricies parturient morbi penatibus sagittis placerat. Vel praesent vitae odio pulvinar consectetur. Feugiat mattis nibh vulputate erat? Sodales cum curae; vulputate. Tristique ridiculus est habitasse porta convallis taciti. Adipiscing integer eu nostra fringilla curae; semper eget amet! Rutrum libero erat arcu nulla, fringilla nisi. Nec malesuada volutpat curabitur montes quam laoreet tellus leo erat. Turpis pharetra libero cubilia.');
insert into temp_lorem_ipsum(data) values ('Elementum cras vivamus, cubilia platea at facilisi quisque elementum. Mi ut lectus habitant! Class commodo, varius cum. Leo, nulla himenaeos vestibulum risus etiam sociis dictumst. Curae; scelerisque enim nunc fermentum penatibus feugiat justo hendrerit semper ipsum! Dapibus fringilla faucibus mollis placerat vitae id libero magnis lacinia. Senectus mauris, rutrum ipsum. Vel etiam dui libero purus augue penatibus ad platea accumsan. Augue ullamcorper urna primis scelerisque. Varius magnis tristique, malesuada consectetur arcu nibh felis. Faucibus laoreet quis, non hendrerit facilisis. Molestie feugiat commodo posuere in habitasse maecenas sed massa litora ligula.');
insert into temp_lorem_ipsum(data) values ('Commodo libero commodo volutpat adipiscing nullam erat netus lorem venenatis placerat odio! Felis urna ad egestas. Augue, mi himenaeos posuere torquent fringilla ac ligula tellus eros vulputate? Potenti massa fringilla litora elit sociis platea lacinia sed odio. Sit parturient egestas pellentesque platea. Etiam suscipit sed donec! Elit mattis; auctor purus quisque aptent. Cursus id litora aptent cursus duis donec libero rhoncus primis phasellus fusce. Class felis iaculis nisl tempor. Himenaeos aliquet dolor neque elementum enim eget. Sed potenti, iaculis vivamus torquent viverra viverra metus? Dictumst primis taciti sem morbi euismod est sodales mauris.');
insert into temp_lorem_ipsum(data) values ('Parturient vivamus mus rutrum euismod nostra blandit orci tempor. Consectetur hac duis interdum imperdiet taciti rhoncus sociis urna euismod sociis augue. Montes urna facilisi volutpat condimentum, sit pharetra suscipit iaculis aliquam. Leo urna litora enim purus lacus purus tincidunt netus cras potenti porta. Suscipit vel malesuada tellus duis magna metus lorem donec egestas eget nascetur mattis. Taciti parturient.');
insert into temp_lorem_ipsum(data) values ('Aptent quis id etiam posuere ullamcorper. Dapibus nascetur, commodo orci? Auctor vulputate porttitor accumsan hendrerit vel. Inceptos, imperdiet venenatis felis sem est. Ridiculus eu purus leo ornare sit euismod faucibus? Cubilia rhoncus, magnis commodo libero malesuada nostra pretium elit. Congue pulvinar massa erat iaculis. Tincidunt sociosqu eu, parturient mauris sapien praesent magnis mi quam a? Ipsum libero dolor.');
insert into temp_lorem_ipsum(data) values ('Fusce, sapien posuere habitant facilisi hac parturient mollis. Feugiat cum dictumst congue faucibus lectus himenaeos scelerisque torquent pellentesque tincidunt ultricies quisque. Curabitur elit, tortor cubilia egestas leo magna a augue nostra taciti netus varius. Fermentum posuere posuere scelerisque. Vulputate molestie sociosqu primis adipiscing augue ac mollis quisque, habitasse mus vel eget? Vitae scelerisque quisque ipsum sed posuere augue inceptos elit quam viverra mauris morbi. Iaculis morbi consectetur bibendum eleifend hendrerit conubia euismod. Sapien ligula inceptos ut pharetra felis penatibus maecenas quisque donec netus. Himenaeos tortor convallis dui eu morbi. Cum pharetra justo penatibus vulputate.');
insert into temp_lorem_ipsum(data) values ('Fusce; sociis inceptos accumsan cursus nec pellentesque orci facilisis pretium? Rhoncus litora dignissim tempor rutrum montes! Suspendisse mauris convallis ad porta ligula et, nam accumsan. Accumsan curae; placerat risus molestie suscipit etiam eget fringilla eleifend dolor senectus? Natoque at cras purus sagittis quisque? Auctor lacinia porta per placerat, molestie dolor bibendum. Convallis quis pharetra sit curabitur aliquet. Amet lobortis semper aliquet. Etiam nec tortor; porttitor lorem. Blandit fusce dui duis egestas? Nunc odio interdum magna. Tincidunt morbi accumsan fermentum morbi!');
insert into temp_lorem_ipsum(data) values ('Eleifend class sociis consequat netus rutrum urna. Cubilia semper nullam porttitor phasellus euismod dignissim dignissim facilisi parturient leo! Elementum fames ullamcorper purus risus taciti ornare vestibulum, vestibulum turpis phasellus gravida in. Pharetra sociosqu dui felis blandit ornare primis id ad condimentum rutrum conubia orci. Amet cras varius mollis mattis mi consectetur facilisi blandit facilisis taciti aliquam class. Nascetur.');
insert into temp_lorem_ipsum(data) values ('Mauris tortor accumsan ultricies blandit non. Arcu commodo consectetur quis ante inceptos. Quisque sed vivamus donec viverra dictum pretium malesuada est pharetra nisl arcu viverra. Accumsan et dignissim, lacinia nibh dictumst habitant lectus adipiscing euismod tellus sapien? Nisi gravida dis consectetur dolor conubia consectetur nec elit. Mi dictum purus tempor cubilia tellus facilisis mollis condimentum dis varius eget congue. Dolor semper sodales nisl tempor curabitur ac iaculis cursus taciti dignissim taciti. Euismod sollicitudin phasellus ultricies nisl, per orci platea maecenas phasellus metus molestie mattis. Litora potenti adipiscing augue sodales accumsan lobortis litora nascetur vivamus luctus litora.');
insert into temp_lorem_ipsum(data) values ('Parturient ridiculus phasellus lobortis mus parturient lectus tempus mi aptent. Duis interdum conubia non varius diam nullam tristique placerat vulputate convallis habitasse. Sapien, ridiculus tristique dui habitant penatibus aptent rutrum! Netus est nunc elit vulputate? Sociis nisi pharetra porttitor fames quam leo? Praesent ante mauris, senectus pulvinar dis quisque aptent enim orci convallis. Sapien bibendum, aenean suscipit. Porttitor posuere tellus feugiat quam non urna fermentum volutpat habitasse ipsum? Amet massa rutrum ac nullam ullamcorper quisque fermentum massa purus lacinia sem.');

-- Generate some reviews
create or replace function generate_ratings() returns void as $$

    declare
        _random_user int;
        _random_rating int;
        _random_comment text;
        _num_ratings_min int = 3;
        _num_ratings_max int = 50;
        _num_ratings int;
        _books_cursor refcursor;
        _record record;
        _book_id varchar(10);
        _book_published_timestamp timestamp without time zone;
        _random_timestamp timestamp without time zone;
    begin
        open _books_cursor for select b.id, b.published from books b where not exists (select * from book_ratings br where br.book_id = b.id);

        loop
            fetch _books_cursor into _record;
            exit when not found;
            _book_id = _record.id;
            _book_published_timestamp = _record.published::timestamp AT TIME ZONE 'UTC';

            -- Generate a random number
            select trunc(random() * _num_ratings_max + _num_ratings_min) into _num_ratings;
            raise notice 'creating % ratings for book %', _num_ratings, _record.id;

            -- Loop through and create that number of ratings
            for i in 1.._num_ratings loop
                -- Who's the lucky user?
                select id from users order by random() limit 1 into _random_user;
                -- What did they rate? (up to 6 since we're flooring down to 5)
                select trunc(random() * 6) into _random_rating;
                -- What did they comment?
                select data from temp_lorem_ipsum order by random() limit 1 into _random_comment;
                -- When did they do it? (sometime between now and when the book was published)
                select _book_published_timestamp + random() * (now() - _book_published_timestamp) into _random_timestamp;

                -- Insert
                insert into book_ratings(book_id, user_id, rating, comment, created_time) VALUES (_book_id, _random_user, _random_rating, _random_comment, _random_timestamp) on conflict do nothing;
            end loop;

        end loop;

        close _books_cursor;
    end;

    $$ language plpgsql;

-- Fire away!
select generate_ratings();

-- Delete the temp data
drop table temp_lorem_ipsum;
drop function generate_ratings();