--create users table
create table users (
    id int generated by default as identity,
    email varchar(255) not null,
    username varchar(255) not null,
    password_hash varchar(255) not null,
    created date default CURRENT_DATE not null,
    UNIQUE(username),
    UNIQUE(email)
);